### ISSUE TITLE
FilePlayer and MP3Shield_Library_Demo example error code 2 

### ISSUE THREAD

**Issue by Angutitsiaq** [mpflaga/Sparkfun-MP3-Player-Shield-Arduino-Library#3]
Hey Michael.

Am using SparkFun MP3 Player Shield and RedBoard. My issue is that a get an error code 2 on the files that I'm testing (aac,wma,ogg). And I know that the error code is: (File not found) I have been reading a lot of comments in the Bills forum but no body mentions about error code 2. And I also read the SFEMP3Shield doxygen reference.
I have done the installation, code uploading and also got the new patches from VLSI correct.  
The mp3 files are playing and working as they should. The funny thing about all this is that I can see the files on the serial monitor when I use your code examples (See the attach files).
I have check my files a couple of time because the error code 2 ( name, format, the right samplerate/Bitrates) and the problem should not be there anymore (if that's should be the problem).

In your code (FilePlayer) you have comment that is should be able to play mp3, aac, wma, wav, fla & mid. should I change something in the code to be able to play the formats?

I hope you have and answer for this problem I'm having.

Regards.
Angut.

![fileplayerarduino](https://cloud.githubusercontent.com/assets/2890566/19721651/83abc5e6-9b73-11e6-9421-45037b171837.PNG)
![fileplayerarduino2](https://cloud.githubusercontent.com/assets/2890566/19721660/8b837160-9b73-11e6-8a23-e04ddeabb401.PNG)

**Comment by mpflaga** [comment]
Looking at your images, i see that it looks like you are using an older version. specifically in the dump of your help I see

" [###] Enter index of file to play, zero pad! e.g. 01-65534"
the current version prints the following:
" [0####] Enter index of file to play, zero pad! e.g. 01-65534"

This is important as I suspect that the problem is that you are not preceding the file index with a ZERO. if the initial digit is 0 then it will used the index location of the directory. example "05" will play "test.aac", where "5" will play "TRACK005.wma". This allows the sketch to be backwards compatible. Leading with a non-zero is the original demo.

I don't have a micro SdCard adapter to explicitly re-try the "aac" format. I do recall validating that it worked. Note that the VS1053 chip does not even see the file name, rather it auto detects the file format. The file extension is simply used to filter out none audio files from the List command. Where the Play command uses the same filter to find the files.

**Comment by mpflaga** [comment]
I just got a SdCard reader/writer and tried out http://techslides.com/demos/samples/sample.aac with the current version FilePlayer.ino and it worked fine.

**Comment by Angutitsiaq** [comment]
I don't get it... 
I just tried the new code and still the same error code 2. (The new code? I downloaded this one/yours) As you can see in the attached pictures I now have the zero "[0####].
I try the music sample you have linked that's working for you, but for me I still get the error code 2.
And when i force the shield to play the specific number a get some really random text out. It looks like that the decoder is missing something. The sample is track 9 & sample.aac

![fileplayerarduinowithnewcode](https://cloud.githubusercontent.com/assets/2890566/19849692/e2916590-9f54-11e6-9bf0-fc26b45d1ea0.PNG)
![fileplayerarduinowithnewcode2](https://cloud.githubusercontent.com/assets/2890566/19849699/ed6463f0-9f54-11e6-9239-5f5dcf3e555c.PNG)

Here you can see my SdCard with it's contents: the plugins and the format. Just to be clear that is not there my problem is. (always a good thing to check with another person)   

![fat32](https://cloud.githubusercontent.com/assets/2890566/19849703/f282c110-9f54-11e6-8fa3-d42a0600bdc9.PNG)

Do you have another suggestion that I could try. Many thanks in advance.

**Comment by Angutitsiaq** [comment]
Hey sorry Michael it actually works. it was my headphones that wasn't put correctly in. 
Thanks a lot for the help... the other files are playing a swell.

**Comment by Angutitsiaq** [comment]
But do you have any suggestion about the decoding text? is it a patch that i need?.

**Comment by mpflaga** [comment]
Noting that there is a difference between playing a Track versus a File by index. I see two pictures up that you are typing "9" and expecting it to play "track009.aac". Actually that is attempting "track009.mp3". When you type "09" or "0009" it then plays identified by index 9, which is identified as "track009.aac", working as you expect. It then looks like index 8 "track008.aac" is played, but some text is missing, that triggered it is missing. Likely lossed in the garbage text.

Regardless, I am glad it is now working for you.

As for the garbage text, the problem is that not all file formats use ID3 tag information. I don't recall which, but really don't think AAC does, I think it is an option that can be added to WAV and MP3. The VS1053 does not actually do the ID3 tag decoding, rather, this library suspends the streaming of the file to the VS1053 then jumps to the end of the file reads in the last 128 bytes, attempts to ID3 tag decode it and then jump back and return to streaming. Other file formats do and don't support tag information, however, there are so many different formats that I did not prioritize that work over demonstrating the VS1053 features. 

You can follow the libraries examples and attempt to decode it yourself they are fairly straight forward, in the following functions: 
SFEMP3Shield::trackArtist(char* infobuffer)
SFEMP3Shield::getTrackInfo(uint8_t offset, char* infobuffer)

**Comment by Angutitsiaq** [comment]
I was just trying out how exactly the file player works, and to see where I could modified it for my own project. I had an idea that it only was meant to work for mp3 tracks but hadn't confirmed it. That's why you could see that I had typed "9" and I expecting it to play. Now its been confirmed, thanks.

About the ID3 tag information it were more a curiosity from my side. I was just wondering if it was a normal problem. I'm sure that i'm not goner use ID3 tags this time, but its good to know how to solve it if it got actual. 
My project now doesn't have a screen so thats why it doesn't really matter. The main purpose for my project is that it should be able to play all the other formats than mp3 and it does. 

I'm currently trying to build a switch based player with only one switch = (box that plays a new song every time its been opened). I am using yours buttonplayer example to develop the code. As it is now, it play only mp3 because I don't really know how to make it to play Index rather then tracks as how you written it. I'm not that good to C-coding yet but I am in progress. Do you have a suggestion how to tangle this problem? I would really appreciate it.

`/**
 * \file MP3ButtonPlayer2.ino
 *
 * \brief Example sketch of using the MP3Shield Arduino driver using buttons,
 * with arduino recommended(simpler) debounce library
 * \remarks comments are implemented with Doxygen Markdown format
 *
 * \author Michael P. Flaga
 *
 * This sketch demonstrates the use of digital input pins used as buttons as 
 * NEXT, PLAY and STOP to control the tracks that are to be played.
 * Where PLAY or STOP will begin or cancel the stream of track000.mp3 through 
 * track999.mp3, as indexed by NEXT, begining with 0.

 * \note Use this example uses the bounce2 library to provide debouncing fuctions. Advocated by Arduino's website at http://playground.arduino.cc/code/bounce
 */

// libraries
#include <SPI.h>
#include <SdFat.h>
#include <SdFatUtil.h>
#include <SFEMP3Shield.h>
#include <Bounce2.h> 

/**
 * \breif Macro for the debounced STOP pin, with pull-up
 */
#define B_STOP  A0

/**
 * \breif Macro for the debounced PLAY pin, with pull-up
 */
#define B_PLAY  A1

/**
 * \breif Macro for the Debounce Period [milliseconds]
 */
#define BUTTON_DEBOUNCE_PERIOD 20 //ms

/**
 * \brief Object instancing the SdFat library.
 *
 * principal object for handling all SdCard functions.
 */
SdFat sd;

/**
 * \brief Object instancing the SFEMP3Shield library.
 *
 * principal object for handling all the attributes, members and functions for the library.
 */
SFEMP3Shield MP3player;

/**
 * \brief Object instancing the Stop Button library.
 */
Bounce b_Stop  = Bounce();

/**
 * \brief Object instancing the Play Button library.
 */
Bounce b_Play  = Bounce();

/**
 * \brief Index of the current track playing.
 *
 * Value indicates current playing track, used to populate "x" for playing the 
 * filename of "track00x.mp3" for track000.mp3 through track254.mp3
 */
int8_t current_track = 0;

//------------------------------------------------------------------------------
/**
 * \brief Setup the Arduino Chip's feature for our use.
 *
 * After Arduino's kernel has booted initialize basic features for this
 * application, such as Serial port and MP3player objects with .begin.
 */
void setup() {
  Serial.begin(115200);

  pinMode(B_STOP, INPUT_PULLUP);
  pinMode(B_PLAY, INPUT_PULLUP);

  b_Stop.attach(B_STOP);
  b_Stop.interval(BUTTON_DEBOUNCE_PERIOD);
  b_Play.attach(B_PLAY);
  b_Play.interval(BUTTON_DEBOUNCE_PERIOD);

  if(!sd.begin(9, SPI_HALF_SPEED)) sd.initErrorHalt();
  if (!sd.chdir("/")) sd.errorHalt("sd.chdir");

  MP3player.begin();
  MP3player.setVolume(10,10);
  
  Serial.println(F("Looking for Buttons to be depressed..."));
}


//------------------------------------------------------------------------------
/**
 * \brief Main Loop the Arduino Chip
 *
 * This is called at the end of Arduino kernel's main loop before recycling.
 * And is where the user's is executed.
 *
 * \note If the means of refilling is not interrupt based then the
 * MP3player object is serviced with the availaible function.
 */
void loop() {

// Below is only needed if not interrupt driven. Safe to remove if not using.
#if defined(USE_MP3_REFILL_MEANS) \
    && ( (USE_MP3_REFILL_MEANS == USE_MP3_SimpleTimer) \
    ||   (USE_MP3_REFILL_MEANS == USE_MP3_Polled)      )

  MP3player.available();
#endif

  if (b_Play.update()) 
  {
    if (b_Play.read() == LOW)	
    {
      Serial.print(F("B_PLAY pressed, Start Playing Track # "));
      Serial.println(current_track = (current_track + 1) % 11);
      MP3player.stopTrack();
      MP3player.playTrack(current_track);
    }
  }

  if (b_Stop.update()) 
  {
    if (b_Stop.read() == LOW)	
    {
      Serial.print(F("B_STOP pressed, Stopping Track #"));
      Serial.println(current_track);
      MP3player.stopTrack();
    }
  }

   //Do something. Have fun with it.

}` 

As you can see in the code, there is still two switches that's because I would like to be able to kill the music when am still in the test phase. And I'm only making it play 10 songs for now.

**Comment by mpflaga** [comment]
You can also see some other quick sketches I have documented helping other persons. There serveral in the OLD button.
https://gist.github.com/mpflaga

Your approach is the quickest. Simply rename the files to track###.mp3. They don't actually have to be MP3 files. So just rename the AAC file to conform. 

Otherwise you will need to re-implement the [code](https://github.com/mpflaga/Sparkfun-MP3-Player-Shield-Arduino-Library/blob/master/SFEMP3Shield/Examples/FilePlayer/FilePlayer.ino#L172) to look something like the below.

```
int16_t fn_index_to_play;


SdFile file;
char filename[13];
sd.chdir("/",true);
uint16_t count = 1;
while (file.openNext(sd.vwd(),O_READ))
{
  file.getFilename(filename);
  if ( isFnMusic(filename) ) {

    if (count == fn_index_to_play++) {
      int8_t result = MP3player.playMP3(filename);
      //check result, see readme for error codes.
      if(result != 0) {
        Serial.print(F("Error code: "));
        Serial.print(result);
        Serial.println(F(" when trying to play track"));
      }
      break;
    }
    count++;
  }
  file.close();
}
```

**Comment by Angutitsiaq** [comment]
Thank you for the big help and the hard work you had put in to this library and code, I really appreciate it.

**Comment by Angutitsiaq** [comment]
Ow... bye the way I did try to approach it by simple changing the names and that's where my hole problem began. It doesn't play the other formats in the button mode (changed names) only mp3 tracks. So I'm going to try to do it the new way you just mentioned.
