### ISSUE TITLE
Playing WAV files

### ISSUE THREAD

**Issue by roryknox** [mpflaga/Sparkfun-MP3-Player-Shield-Arduino-Library#4]
The FilePlayer sketch says it can play WAV files, among others, but I can't get it to play a WAV file. Is something missing? Rory

**Comment by mpflaga** [comment]
The VS1053 chip itself reads the content of the streamed file as to determine the file format. In other words the filename suffix is irrelevant, the Arduino is not involved with this aspect. The suffix can be omitted and or even erroneous. Where the example code does use the suffix to filter, as to list only ".mp3", ".aac", ".wma", ".wav", ".fla", ".mid" applicable files in the directory. 

That said, I have seen this library regularly play WAV and other types of files, not just MP3's. Also not that WAV format is really just a header, that indicates the actual encoding format of the data later within the file. It is possible there is an encoding format that is not supported by the VS1053. Please ensure the patches.053 file is located on the SdCard's root, so that it can be applied. I assume you have validated that a read back of the file from the SdCard does play with a different player. If that is the case I would assume it is an unsupported encoding.  If this is the case I would recommend re-encoding the file. Using something like Audacity to read the file, make sure it can play it. And then Export the file as a different format, such as MP3.

**Comment by roryknox** [comment]
Thank you for your helpful email. The WAV files I am using are entirely standard. I have been using them with other devices for years. What happens is this:
When I use the command MP3player.playTrack(x) to play a WAV file it can't find the track. When I useMP3player.playMP3(...) with a WAV file it does play but the sound is garbled. When I use MP3player.playTrack(x) to play a WMA file it can't find the track. When I useMP3player.playMP3(...) with a WMA file I get silence. Maybe there is another command that I don't know about.

MP3 files play perfectly with either command.

Is the patches.053 file essential for MP3s to play? If so it must be there, although I don't see it anywhere in the libraries. It is not on the SD card.

 I have no need to play WMA files - I tried one just as an experiment. What I really want is to play WAV. If you are able to show me how to do that, that would be wonderful.
Regards,
Rory Johnston

**Comment by mpflaga** [comment]
the patch is a plug in, it can be located at https://github.com/mpflaga/Sparkfun-MP3-Player-Shield-Arduino-Library/tree/master/plugins . It is not required for more files, it has bug fixes for the VS1053 dsp code. 

please note that the below function
`SFEMP3Shield::playTrack(uint8_t trackNo) `

will only play filenames ending in the extension of "mp3", as shown in the below code snippet.
`sprintf(trackName, "track%03d.mp3", trackNo);`
This means that "track001.wav" will not play using the playTrack function. Rather the `SFEMP3Shield::playMP3(char* fileName)` is needed to play other filename extensions.

Have you tried changing the name of your desired file to "track001.mp3".

Note that MP3Shield_Library_Demo.ino, can only use the playTrack() function. That is why I created FilePlayer.ino it also allows playMP3(). Both though are limited to 8.3 file name format. So do not exceed 8.3.

**Comment by roryknox** [comment]
Thanks for your email. Could you please tell me what I am supposed to do to play a WAV file? If the file is called "symphony.wav" should I just give the commands:
char trackName[] = "symphony.wav";
MP3player.playMP3(trackName);
As I told you, when I do this the sound comes out garbled. When I do the same with a WMA file there is silence. What do I need to do to get the sound to play correctly? As I said, the WAV file is standard.

I note that your email says SFEMP3Shield::playMP3(...) rather than MP3player.playMP3(...) but since the FilePlayer sketch uses the latter I assume this does not matter.
Rory Johnston

**Comment by mpflaga** [comment]
you are correct for MP3player.playMP3(trackName); is the correct method for FilePlayer.ino
I am not able to answer why your current wave file is not able to be played. I would recommend using Audacity (or SOX or similar) to re-encode the file. 

Also note there several other examples in my GIST account that can be seen at https://gist.github.com/mpflaga . They wont help your wav issue, but do provide a few other examples for buttons, random and other typical use cases.

**Comment by mpflaga** [comment]
No comment since, closing
